services:
  - type: web
    name: games-catalog-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        sync: false # Установите URL вашего API на Render
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 